Repository commercetools/test-data, pull requests merged in 2023-09, with the labels that each got.

#332 chore(test-data): fix `StoreDraft.name` graphql type
  .changeset/large-worms-peel.md
  models/store/src/store/store-draft/presets/sample-data-fashion/store-01.spec.ts
  models/store/src/store/store-draft/presets/sample-data-fashion/store-02.spec.ts
  models/store/src/store/store-draft/presets/sample-data-fashion/store-03.spec.ts
  models/store/src/store/store-draft/transformers.ts
  models/store/src/store/types.ts
Labels: bug

#359 chore(test-data): goodstore cart discount and discount code presets
  .changeset/sour-planes-bow.md
  models/cart-discount/src/cart-discount/cart-discount-draft/presets/index.ts
  models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/free-shipping.spec.ts
  models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/free-shipping.ts
  models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/furniture-bogo.spec.ts
  models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/furniture-bogo.ts
  models/cart-discount/src/cart-discount/cart-discount-draft/presets/sample-data-goodstore/index.ts
  models/discount-code/src/discount-code-draft/presets/index.ts
  models/discount-code/src/discount-code-draft/presets/sample-data-goodstore/furniture-bogo.spec.ts
  models/discount-code/src/discount-code-draft/presets/sample-data-goodstore/furniture-bogo.ts
  models/discount-code/src/discount-code-draft/presets/sample-data-goodstore/index.ts
Labels: enhancement

#361 chore(test-data): Good Store product type presets
  .changeset/wise-teachers-impress.md
  models/product-type/src/attribute-definition/attribute-definition-draft/presets/empty.spec.ts
  models/product-type/src/attribute-definition/attribute-definition-draft/presets/empty.ts
  models/product-type/src/index.ts
  models/product-type/src/product-type/product-type-draft/presets/index.ts
  models/product-type/src/product-type/product-type-draft/presets/sample-data-goodstore/bedding-bundle.spec.ts
  models/product-type/src/product-type/product-type-draft/presets/sample-data-goodstore/bedding-bundle.ts
  models/product-type/src/product-type/product-type-draft/presets/sample-data-goodstore/furniture-and-decor.spec.ts
  models/product-type/src/product-type/product-type-draft/presets/sample-data-goodstore/furniture-and-decor.ts
  models/product-type/src/product-type/product-type-draft/presets/sample-data-goodstore/index.ts
  models/product-type/src/product-type/product-type-draft/presets/sample-data-goodstore/product-sets.spec.ts
  models/product-type/src/product-type/product-type-draft/presets/sample-data-goodstore/product-sets.ts
Labels: enhancement

#367 bug(test-data): corrections to lenum, set, and reference transformations
  .changeset/early-dodos-scream.md
  models/product-type/src/attribute-localized-enum-type/attribute-localized-enum-type-draft/builder.spec.ts
  models/product-type/src/attribute-localized-enum-type/attribute-localized-enum-type-draft/generator.ts
  models/product-type/src/attribute-localized-enum-type/attribute-localized-enum-type-draft/transformers.ts
  models/product-type/src/attribute-localized-enum-type/types.ts
  models/product-type/src/attribute-reference-type/attribute-reference-type-draft/builder.spec.ts
  models/product-type/src/attribute-reference-type/attribute-reference-type-draft/generator.ts
  models/product-type/src/attribute-reference-type/attribute-reference-type-draft/transformers.ts
  models/product-type/src/attribute-reference-type/types.ts
  models/product-type/src/attribute-set-type/attribute-set-type-draft/builder.spec.ts
  models/product-type/src/attribute-set-type/attribute-set-type-draft/generator.ts
  models/product-type/src/attribute-set-type/attribute-set-type-draft/transformers.ts
  models/product-type/src/attribute-set-type/types.ts
  models/product-type/src/product-type/product-type-draft/presets/sample-data-goodstore/bedding-bundle.spec.ts
  models/product-type/src/product-type/product-type-draft/presets/sample-data-goodstore/furniture-and-decor.spec.ts
  models/product-type/src/product-type/product-type-draft/presets/sample-data-goodstore/product-sets.spec.ts
Labels: bug

#368 FCT-499: Shipping methods
  .changeset/lucky-plums-applaud.md
  models/shipping-method/src/shipping-method/shipping-method-draft/presets/index.ts
  models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-goodstore/express.spec.ts
  models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-goodstore/express.ts
  models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-goodstore/index.ts
  models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-goodstore/standard.spec.ts
  models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-goodstore/standard.ts
  models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-goodstore/usa.spec.ts
  models/shipping-method/src/shipping-method/shipping-method-draft/presets/sample-data-goodstore/usa.ts
  models/shipping-method/src/shipping-rate/shipping-rate-draft/presets/index.ts
  models/shipping-method/src/shipping-rate/shipping-rate-draft/presets/sample-data-goodstore/eur-10000.spec.ts
  models/shipping-method/src/shipping-rate/shipping-rate-draft/presets/sample-data-goodstore/eur-10000.ts
  models/shipping-method/src/shipping-rate/shipping-rate-draft/presets/sample-data-goodstore/eur-50000.spec.ts
  models/shipping-method/src/shipping-rate/shipping-rate-draft/presets/sample-data-goodstore/eur-50000.ts
  models/shipping-method/src/shipping-rate/shipping-rate-draft/presets/sample-data-goodstore/gbp-10000.spec.ts
  models/shipping-method/src/shipping-rate/shipping-rate-draft/presets/sample-data-goodstore/gbp-10000.ts
  models/shipping-method/src/shipping-rate/shipping-rate-draft/presets/sample-data-goodstore/gbp-50000.spec.ts
  models/shipping-method/src/shipping-rate/shipping-rate-draft/presets/sample-data-goodstore/gbp-50000.ts
  models/shipping-method/src/shipping-rate/shipping-rate-draft/presets/sample-data-goodstore/index.ts
  models/shipping-method/src/shipping-rate/shipping-rate-draft/presets/sample-data-goodstore/usd-5000.spec.ts
  models/shipping-method/src/shipping-rate/shipping-rate-draft/presets/sample-data-goodstore/usd-5000.ts
  models/shipping-method/src/zone-rate/zone-rate-draft/presets/index.ts
  models/shipping-method/src/zone-rate/zone-rate-draft/presets/sample-data-goodstore/europe-express.spec.ts
  models/shipping-method/src/zone-rate/zone-rate-draft/presets/sample-data-goodstore/europe-express.ts
  models/shipping-method/src/zone-rate/zone-rate-draft/presets/sample-data-goodstore/europe.spec.ts
  models/shipping-method/src/zone-rate/zone-rate-draft/presets/sample-data-goodstore/europe.ts
  models/shipping-method/src/zone-rate/zone-rate-draft/presets/sample-data-goodstore/index.ts
  models/shipping-method/src/zone-rate/zone-rate-draft/presets/sample-data-goodstore/united-kingdom.spec.ts
  models/shipping-method/src/zone-rate/zone-rate-draft/presets/sample-data-goodstore/united-kingdom.ts
  models/shipping-method/src/zone-rate/zone-rate-draft/presets/sample-data-goodstore/usa.spec.ts
  models/shipping-method/src/zone-rate/zone-rate-draft/presets/sample-data-goodstore/usa.ts
  models/zone/src/zone/zone-draft/presets/sample-data-goodstore/country-usa.spec.ts
  models/zone/src/zone/zone-draft/presets/sample-data-goodstore/country-usa.ts
  models/zone/src/zone/zone-draft/presets/sample-data-goodstore/index.ts
Labels: ready for review 🙌
